In [1]:
import pandas as pd

In [2]:
location = pd.read_csv("Linear.csv")
location.head()

initial_position  initial_velocity  mass  time  location
0               991                46   492    37   -4015.1
1              3693                58   447    92  -32444.6
2              6666                55   604    79  -19569.9
3              1286                 2   859    78  -28369.6
4              5921                19   907    32    1511.4

In [3]:
y = location['location']
x = location.drop(['mass','location'],axis=1)

In [4]:
y

0       -4015.1
1      -32444.6
2      -19569.9
3      -28369.6
4        1511.4
         ...   
9995     5524.6
9996     2453.0
9997     7297.4
9998    -1113.5
9999     -848.4
Name: location, Length: 10000, dtype: float64

In [5]:
x

initial_position  initial_velocity  time
0                  991                46    37
1                 3693                58    92
2                 6666                55    79
3                 1286                 2    78
4                 5921                19    32
...                ...               ...   ...
9995              6163                23    14
9996              3893                99    30
9997              7727                23    12
9998              3314                45    35
9999              8738                17    46

[10000 rows x 3 columns]

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state=30)

In [7]:
x_train.size

24000

In [8]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [9]:
model = LinearRegression()
poly = PolynomialFeatures(degree=2)
x_train_transformed = poly.fit_transform(x_train)
x_test_transformed = poly.fit_transform(x_test)

In [10]:
model.fit(x_train_transformed,y_train)

LinearRegression()

In [11]:
model.coef_

array([ 0.00000000e+00,  1.00000000e+00, -8.94693275e-13, -2.54849563e-13,
        0.00000000e+00, -1.26201133e-15, -1.39471767e-15, -1.08311797e-14,
        1.00000000e+00, -4.90000000e+00])

In [13]:
y_pred = model.predict(x_test_transformed)

In [14]:
y_test

8793   -24997.1
1122       56.9
1283     2478.5
9318   -10516.1
7765      772.1
         ...   
7142   -25058.1
8826     6304.1
4553     7771.6
5795   -11478.1
3797    -6471.1
Name: location, Length: 2000, dtype: float64

In [15]:
y_pred

array([-24997.1,     56.9,   2478.5, ...,   7771.6, -11478.1,  -6471.1])

In [16]:
from sklearn.metrics import mean_squared_error

In [17]:
print("MSE: ",mean_squared_error(y_test,y_pred))

MSE:  4.36034765032715e-18


In [21]:
import numpy as np
new_values = np.array([[0,60,10]])
poly = PolynomialFeatures(degree=2)
new_values_transformed = poly.fit_transform(new_values)
print(new_values_transformed)

[[1.0e+00 0.0e+00 6.0e+01 1.0e+01 0.0e+00 0.0e+00 0.0e+00 3.6e+03 6.0e+02
  1.0e+02]]


In [22]:
model.predict(new_values_transformed)

array([110.])